Adição repositórios de Swift
leticiadasilva/Hacktoberfest pull request #2
Opened 2020-10-06 19:12 UTC by ViniciusDeep

* Adição repositórios de Swift

2020-10-06 21:04 UTC, leticiadasilva requested changes

2020-10-06 21:04 UTC, leticiadasilva commented on repositorios.md
> +- https://github.com/MessageKit/MessageKit
Opa Vinicius, tu consegue colocar o nome entre [] e os links entre ()? 

Ex: [Revill](https://github.com/ViniciusDeep/Revill)

É pra manter no padrão do repositório :smile:

2020-10-07 20:21 UTC, ViniciusDeep commented on repositorios.md
> +- https://github.com/MessageKit/MessageKit
@leticiadasilva Feito

2020-10-07 21:21 UTC, merged

2020-10-07 21:22 UTC, leticiadasilva commented on repositorios.md
> +- https://github.com/MessageKit/MessageKit
Opa, aceitei!

2020-10-07 21:22 UTC, leticiadasilva commented
Obrigada!!! <3